### ISSUE TITLE
snap 1.0

### ISSUE THREAD

**Issue by imalsogreg** [dbp/hspec-snap#21]
Would you mind having a branch targeting snap 1.0? If you don't already have one in the works I can try to get it working and send a PR along with a script to grab the dependencies from github (until 1.0 gets released).

**Comment by dbp** [comment]
No that sounds great. Do you know if it is any closer to being released? It's been "almost ready" now for... years.

**Comment by imalsogreg** [comment]
I don't know. I have a growing pile of stuff depending on it, so soon hopefully :) I was trying to help with the benchmarking report, stalled out on that for (checking watch) the past few months. I've heard that it's mostly a matter of documentation and website updates.

**Comment by imalsogreg** [comment]
Thanks for the quick merge!
